# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: coder nirvana
email: bvivek35@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Where pragmatism crosses software engineering
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://bvivek35.github.com" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  bvivek35
disqus: "bvivek35-github-io"

# Build settings
markdown: kramdown
highlighter: rouge

plugins:
  - jekyll-feed
  - jekyll-remote-theme
  - jekyll-sitemap
  - jekyll-mentions
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-redirect-from
  - jekyll-default-layout
  - jekyll-feed
  - jemoji


remote_theme: daviddarnes/alembic

paginate: 1 # jekyll-paginate > items per page
paginate_path: /blog/page:num # jekyll-paginate > blog page

navigation_header:
  Home: /
  Elements: /elements/
  Blog: /blog/
  Categories: /categories/
  Search: /search/
  About: /about/

navigation_footer:
  Created by Vivek Bharadwaj: https://bvivek35.github.io

sharing_links: # Appear at the bottom of single blog posts, uncomment and comment out as desired. Colours set the button colour
  Email: "bvivek35@gmail.com"

